// Committed content snapshot (AGENTS.md › Deployment). The data lives in src/lib/content/
// (`works.json` / `blocks.json` / `meta.json` / `images/`), generated by
// `scripts/export-content.mjs` from PocketBase — never hand-edit it, run `npm run
// export-content` instead. This module sits under $lib/server on purpose: SvelteKit then
// refuses any browser import, which would pull all snapshot images into the client bundle. Server loaders (`$lib/server/works.ts`,
// `$lib/server/content.ts`) fall back to this snapshot when the CMS is unreachable, so the
// static site can build with no backend at all.
import type { Work } from '$lib/data/works';
import worksData from '$lib/content/works.json';
import blocksData from '$lib/content/blocks.json';
import metaData from '$lib/content/meta.json';

type SnapshotWork = {
	id: string;
	collection: 'gallery' | 'sketch';
	sort: number | null;
	title_zh: string;
	title_en: string;
	description_zh: string;
	description_en: string;
	year: number | null;
	medium: string;
	size: string;
	sold: boolean;
	image: string;
	source_image: string;
};

type SnapshotBlock = { zh: string; en: string };

export type SnapshotMeta = { exported_at: string; source: string; works: number; blocks: number };

const works = worksData as SnapshotWork[];
const blocks = blocksData as Record<string, SnapshotBlock>;
export const snapshotMeta: SnapshotMeta = metaData as SnapshotMeta;

// Vite eagerly resolves every snapshot image to its build URL, keyed by the `<id>.jpg`
// filename the export script writes. Files under 4 KB would be base64-inlined instead
// (assetsInlineLimit); the exporter refuses such files. Relative path: Vite's glob is more
// reliable with literal relative patterns than with aliases.
const imageModules = import.meta.glob('../content/images/*.jpg', {
	eager: true,
	query: '?url',
	import: 'default'
}) as Record<string, string>;

const imageUrlById = new Map<string, string>();
for (const [path, url] of Object.entries(imageModules)) {
	const id = (path.split('/').pop() ?? '').replace(/\.jpg$/, '');
	imageUrlById.set(id, url);
}

function bilingual(zh: string, en: string): string {
	if (zh && en) return `${zh} · ${en}`;
	return zh || en;
}

/**
 * Published works for one collection, from the committed snapshot — same shape and bilingual
 * rule as `toWork` in `$lib/server/works.ts`. Ordered by `sort`, ties broken by export order
 * (the snapshot is already sorted `collection,sort,-created`). A work with no matching image
 * (snapshot/images out of sync) is skipped with a loud warning instead of breaking the build.
 */
export function snapshotWorks(collection: 'gallery' | 'sketch'): Work[] {
	return works
		.filter((w) => w.collection === collection)
		.sort((a, b) => (a.sort ?? 0) - (b.sort ?? 0))
		.flatMap((w): Work[] => {
			const url = imageUrlById.get(w.id);
			if (!url) {
				console.warn(
					`[content snapshot] work ${w.id} ("${w.title_zh || w.title_en}") has no matching image in src/lib/content/images/ — skipped. Re-run "npm run export-content".`
				);
				return [];
			}
			const title = bilingual(w.title_zh, w.title_en);
			return [
				{
					src: url,
					hires: url,
					alt: title,
					title,
					year: w.year ? String(w.year) : '',
					medium: w.medium ?? '',
					size: w.size ?? '',
					sold: w.sold || undefined
				}
			];
		});
}

export type Blocks = Record<string, SnapshotBlock>;

/** Content blocks by slug, from the committed snapshot. Missing slugs are simply absent. */
export function snapshotBlocks(slugs: string[]): Blocks {
	const out: Blocks = {};
	for (const slug of slugs) {
		const block = blocks[slug];
		if (block) out[slug] = block;
	}
	return out;
}
